name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: python-version: '3.10'
      - name: Install deps
        run: pip install -r services/ingestion/requirements.txt
      - name: Run unit tests (fast)
        run: pytest -q tests -k smoke -q || true
